name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
      - name: Zip files
        run: zip -r "辞書データ.zip" "辞書データ"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: 辞書データ.zip
          body_path: .github/workflows/RELEASE_NOTE.md
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}